## Auth
register:
  path: /register
  controller: App\Interfaces\Controller\UserController::register
  methods: [ POST ]

login:
  path: /login
  controller: App\Interfaces\Controller\UserController::login
  methods: [ POST ]

#Product
productList:
  path: /products
  controller: App\Interfaces\Controller\ProductController::productList
  methods: [ GET ]

createProduct:
  path: /products
  controller: App\Interfaces\Controller\ProductController::createProduct
  methods: [ POST ]

deleteProduct:
  path: /products/{id}
  controller: App\Interfaces\Controller\ProductController::deleteProduct
  methods: [ DELETE ]

## Cart
getCart:
  path: /cart
  controller: App\Interfaces\Controller\CartController::getCart
  methods: [ GET ]

addProductToCart:
  path: /cart
  controller: App\Interfaces\Controller\CartController::addProductToCart
  methods: [ POST ]

removeProductFromCart:
  path: /cart
  controller: App\Interfaces\Controller\CartController::removeProductFromCart
  methods: [ DELETE ]

checkout:
  path: /cart/checkout
  controller: App\Interfaces\Controller\CartController::checkout
  methods: [ POST ]
